apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charlesd-sorn-sweep-storage
  namespace: hengenlab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs   # replace if kubectl get storageclass showed a different name
  resources:
    requests:
      storage: 600Gi ## 1*450 + 150 wiggle room